apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycoffeeapp
spec:
  selector:
    matchLabels:
      app: mycoffeeapp
  template:
    metadata:
      labels:
        app: mycoffeeapp
    spec:
      containers:
      - name: mycoffeeapp
        image: abdelrahman2arafa/node.js_coffe
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: "256Mi"
            cpu: "1"
        ports:
        - containerPort: 80
        env:
        - name: APP_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: APP_HOST
        - name: APP_DB_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: APP_DB_USER
        - name: APP_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: APP_DB_NAME
        - name: APP_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: APP_DB_PASSWORD
