apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: a4-project
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-service
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: abdelrahman2arafa/mysql_coffe
  volumes:
  - name: mysql-persistent-storage
    persistentVolumeClaim:
      claimName: mysql-pvc
