apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: a4-project
spec:
  selector:
    app: mysql-service
  ports:
    - protocol: TCP
      port:  3306
      targetPort: 3306
  type: ClusterIP 
